config/routes.rb
Rails.application.routes.draw do
  resources :decks do
    resources :flashcards
  end
  devise_for :users
  root 'home#index'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :flashcards
end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
  belongs_to :deck
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :decks
  has_many :flashcards, through: :decks
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /decks
  # GET /decks.json
  def index
    @decks = current_user.decks.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = current_user.decks.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = current_user.decks.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = current_user.decks.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name, :description, :recent, :user_id)
    end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :new, :update, :destroy]
  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcards = current_user.flashcards.all
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
  end

  # GET /flashcards/new
  def new
    @flashcard = @deck.flashcards.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to deck_flashcards_path, notice: 'Flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flashcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to deck_flashcards_path(@deck), notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'Flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @deck = current_user.decks.find(params[:deck_id])
      if @deck.flashcards.find_by(params[:id])
        @flashcard = @deck.flashcards.find_by(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flashcard_params
      params.require(:flashcard).permit(:id, :front, :back, :recent, :deck_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :recent %><br>
    <%= f.number_field :recent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Recent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= deck.description %></td>
        <td><%= deck.recent %></td>
        <td><%= link_to 'cards', deck_flashcards_path(deck) %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deck.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deck.description %>
</p>

<p>
  <strong>Recent:</strong>
  <%= @deck.recent %>
</p>

<p>
  <strong>User:</strong>
  <%= @deck.user %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/flashcards/_form.html.erb
<%= form_for @flashcard, url: deck_flashcards_path do |f| %>
  <% if @flashcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flashcard.errors.count, "error") %> prohibited this flashcard from being saved:</h2>

      <ul>
      <% @flashcard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :front %><br>
    <%= f.text_field :front %>
  </div>
  <div class="field">
    <%= f.label :back %><br>
    <%= f.text_field :back %>
  </div>
  <div class="field">
    <%= f.label :recent %><br>
    <%= f.number_field :recent %>
  </div>
  <div class="field">
    <%= f.label :deck_id %><br>
    <%= f.text_field :deck_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flashcards/edit.html.erb
<h1>Editing Flashcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @flashcard %> |
<%= link_to 'Back', flashcards_path %>

app/views/flashcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flashcards</h1>

<table>
  <thead>
    <tr>
      <th>Front</th>
      <th>Back</th>
      <th>Recent</th>
      <th>Deck</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flashcards.each do |flashcard| %>
      <tr>
        <td><%= flashcard.front %></td>
        <td><%= flashcard.back %></td>
        <td><%= flashcard.recent %></td>
        <td><%= flashcard.deck %></td>
        <td><%= link_to 'Show', deck_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Edit', edit_deck_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Destroy', deck_flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flashcard', new_deck_flashcard_path %>

app/views/flashcards/new.html.erb
<h1>New Flashcard</h1>

<%= render 'form' %>

<%= link_to 'Back', deck_flashcards_path %>

app/views/flashcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Front:</strong>
  <%= @flashcard.front %>
</p>

<p>
  <strong>Back:</strong>
  <%= @flashcard.back %>
</p>

<p>
  <strong>Recent:</strong>
  <%= @flashcard.recent %>
</p>

<p>
  <strong>Deck:</strong>
  <%= @flashcard.deck %>
</p>

<%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
<%= link_to 'Back', flashcards_path %>

app/views/home/index.html.erb
<%=provide(:title, "flash") %>
<div class="container">
  <div class="jumbotron">
    <h1>Welcome to flash!</h1>
    <p class="center">flash is a flashcards rails app</p>
  </div>

<div class="center">
  <% if !current_user.nil? %>
    <%= link_to 'hello', decks_path(current_user) %>
  <% else %>
    <%= link_to 'signup', new_user_registration_path, class: 'btn btn-default btn-lg' %>
    <% end %>
  </div>
</div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="nav navbar-fixed-top">
    <div class="logo"><%= link_to "flash", root_path %></div>
    <nav>
      <ul class="rheader">
          <% if !current_user.nil? %>
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "settings", edit_user_registration_path(current_user) %></li>
                <li>
                <%= link_to "logout", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "login", new_user_session_path %></li>
          <% end %>
      </ul>
    </nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice || alert %>
  <p class="notice notice-success"><%= notice %></p>
  <p class="alert alert-success"><%= alert %></p>
<% end %>
<%= render '/layouts/header' %>
<div class="container"><%= yield %></div>

</body>
</html>